version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-placar
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: placar_arena
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

volumes:
  dbdata:
